# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapHubPlugin
                                 A QGIS plugin
 Plugin that allows view, edit, download and upload maps to and from MapHub
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-01
        copyright            : (C) 2025 by MapHub
        email                : maphub@meteory.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapHubPlugin class from file MapHubPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MapHubPlugin import MapHubPlugin
    return MapHubPlugin(iface)
